// Generates supabase/seed.sql from src/data/fallback.ts so the database seed and the
// in-app fallback content are always identical.  Usage: npm run seed:gen
import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const result = await build({
  entryPoints: [path.join(root, 'src/data/fallback.ts')],
  bundle: true,
  format: 'esm',
  platform: 'node',
  write: false,
});
const code = result.outputFiles[0].text;
const { FALLBACK_SERVICES, FALLBACK_CLIENTS } = await import(
  'data:text/javascript;base64,' + Buffer.from(code).toString('base64')
);

const str = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const json = (v) => `${str(JSON.stringify(v))}::jsonb`;
const arr = (v) => (v.length ? `array[${v.map(str).join(', ')}]::text[]` : `'{}'::text[]`);

const lines = [
  '-- GENERATED by scripts/gen-seed.mjs from src/data/fallback.ts. Do not edit by hand:',
  '-- change fallback.ts and run `npm run seed:gen`.',
  '-- Safe to run more than once: rows are upserted on slug.',
  '',
  'insert into public.services',
  '  (slug, category, priority, title, tagline, summary, description, icon, features, process, deliverables, faqs, industries, is_featured)',
  'values',
  FALLBACK_SERVICES.map(
    (s) =>
      `  (${[
        str(s.slug),
        str(s.category),
        s.priority,
        str(s.title),
        str(s.tagline),
        str(s.summary),
        str(s.description),
        str(s.icon),
        json(s.features),
        json(s.process),
        arr(s.deliverables),
        json(s.faqs),
        arr(s.industries),
        s.is_featured ? 'true' : 'false',
      ].join(',\n   ')})`,
  ).join(',\n'),
  'on conflict (slug) do update set',
  '  category = excluded.category, priority = excluded.priority, title = excluded.title,',
  '  tagline = excluded.tagline, summary = excluded.summary, description = excluded.description,',
  '  icon = excluded.icon, features = excluded.features, process = excluded.process,',
  '  deliverables = excluded.deliverables, faqs = excluded.faqs, industries = excluded.industries,',
  '  is_featured = excluded.is_featured;',
  '',
  'insert into public.clients (slug, name, sector, logo_url, website_url, sort_order)',
  'values',
  FALLBACK_CLIENTS.map(
    (c) => `  (${[str(c.slug), str(c.name), str(c.sector), str(c.logo_url), str(c.website_url), c.sort_order].join(', ')})`,
  ).join(',\n'),
  'on conflict (slug) do update set',
  '  name = excluded.name, sector = excluded.sector, sort_order = excluded.sort_order;',
  '',
];

await writeFile(path.join(root, 'supabase/seed.sql'), lines.join('\n'), 'utf8');
console.log(`seed.sql written: ${FALLBACK_SERVICES.length} services, ${FALLBACK_CLIENTS.length} clients`);
